services:
  app:
    container_name: studio-booking-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/src
      - studio-booking-api-modules:/src/node_modules
    environment:
      - PORT=${PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - studio-booking-api-network
    command: npm run start

  db:
    image: postgres:alpine
    container_name: studio-booking-api-database
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d tasks']
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - studio-booking-api-network

networks:
  studio-booking-api-network:
    driver: bridge

volumes:
  studio-booking-api-modules:
  postgres_data:
    driver: local
  redis-data:
